<a href="https://colab.research.google.com/github/MdFurqan2000/deep-learning-ANN/blob/main/deep_learning_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.9.2


In [ ]:
## importing libraries
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset=pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
#seperating the dataset 
X=dataset.iloc[:,3:13]
y=dataset.iloc[:,13]

In [ ]:
X.head(3)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57

In [ ]:
y.head(3)

0    1
1    0
2    1
Name: Exited, dtype: int64

In [ ]:
pd.get_dummies(X['Geography'],drop_first=True)

Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]

In [ ]:
geography=pd.get_dummies(X['Geography'],drop_first=True)

In [ ]:
gender=pd.get_dummies(X['Gender'],drop_first=True)

In [ ]:
gender.head(2)

Male
0     0
1     0

In [ ]:
X=X.drop(['Geography','Gender'],axis=1)

In [ ]:
X.head(3)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   

   IsActiveMember  EstimatedSalary  
0               1        101348.88  
1               1        112542.58  
2               0        113931.57

In [ ]:
#concatination
X=pd.concat([X,geography,gender],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
#feature scaling

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [ ]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [ ]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [ ]:
X_train.shape

(8000, 11)

In [ ]:
### Now lets creat ANN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LeakyReLU, PReLU, ELU, ReLU
from tensorflow.keras.layers import Dropout


In [ ]:
# lets initialize the ANN
Classifier=Sequential()


In [ ]:
# adding the input layer
Classifier.add(Dense(units=11,activation='relu'))

In [ ]:
# adding the first hidden layer
Classifier.add(Dense(units=7,activation='relu'))

In [ ]:
# adding the second hidden layer
Classifier.add(Dense(units=6,activation='relu'))

In [ ]:
## adding the output layer
Classifier.add(Dense(units=1,activation='sigmoid'))

In [ ]:
Classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
model_history=Classifier.fit(X_train,y_train,validation_split=0.33,batch_size=10,epochs=50)

Epoch 1/50
536/536 [==============================] - 5s 4ms/step - loss: 0.5190 - accuracy: 0.7919 - val_loss: 0.4474 - val_accuracy: 0.7955
Epoch 2/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4310 - accuracy: 0.7962 - val_loss: 0.4323 - val_accuracy: 0.7955
Epoch 3/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4208 - accuracy: 0.7962 - val_loss: 0.4272 - val_accuracy: 0.7955
Epoch 4/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4141 - accuracy: 0.7962 - val_loss: 0.4222 - val_accuracy: 0.7955
Epoch 5/50
536/536 [==============================] - 2s 4ms/step - loss: 0.4072 - accuracy: 0.8162 - val_loss: 0.4155 - val_accuracy: 0.8194
Epoch 6/50
536/536 [==============================] - 2s 4ms/step - loss: 0.3992 - accuracy: 0.8328 - val_loss: 0.4083 - val_accuracy: 0.8232
Epoch 7/50
536/536 [==============================] - 2s 4ms/step - loss: 0.3916 - accuracy: 0.8373 - val_loss: 0.4019 - val_accuracy: 0.8281
Epoch 

In [ ]:
model_history.history.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [ ]:
## now making the predictions and evaluating the model
y_pred = Classifier.predict(X_test)
y_pred = (y_pred >= 0.5)

63/63 [==============================] - 0s 1ms/step


In [ ]:
# making the confusion matrix
from sklearn.metrics import confusion_matrix

In [ ]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[1498,   97],
       [ 190,  215]])

In [ ]:
## Calculating the accuracy
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)

In [ ]:
score

0.8565

In [ ]:
## to get the weights 
Classifier.get_weights()

[array([[ 1.8689233e-01, -5.3849602e-03, -6.8441235e-02,  2.4389027e-01,
          3.1356573e-01, -1.9818240e-01, -5.9717033e-02,  6.9027580e-02,
          4.8618227e-02,  7.3894121e-02, -3.6388314e-01],
        [ 3.3300871e-01,  1.6866948e-01,  1.2839624e-02, -7.3497295e-02,
         -2.7881858e-01,  1.5609473e-01,  4.7863880e-01, -7.2550088e-02,
          6.0547131e-01, -6.3071913e-01, -2.4324298e-01],
        [-9.1419900e-03, -9.5714808e-02,  2.4023665e-01, -2.2825328e-01,
         -9.5638558e-02, -7.2009757e-02, -1.3608381e-01, -5.5750698e-01,
          3.5007115e-02, -1.0660378e-01,  5.7440978e-01],
        [ 1.2463517e-01,  4.8044249e-01,  4.5385063e-01,  1.5155266e-01,
         -1.7700179e-01,  2.7214247e-01, -1.5969364e-01,  3.4941581e-01,
          1.0854489e-01,  1.0410701e-03,  1.6153103e-01],
        [ 8.4096473e-01,  1.0991675e+00,  8.4372568e-01,  8.2612222e-01,
          5.4739171e-01,  1.1237261e-01, -1.3194172e+00,  4.4749003e-02,
          2.6330912e-01,  4.0525892e-0